### ISSUE TITLE
Only lists a few repositories of a user

### ISSUE THREAD

**Issue by wopian** [codescientist703/github-kanban#1] opened 2021-05-25 16:48 UTC
I found this from your Reddit post and filled it in with my username to check it out. Unfortunately it only seems to show ~~4~~ 5 repositories with contributions and their subsequent issues/PRs: https://codescientist703.github.io/github-kanban/?user=wopian

I have somewhere around ~100 open issues or PRs in total from [GitHub's own dashboard](https://github.com/issues?q=is%3Aopen+author%3Awopian+archived%3Afalse)

**Comment by codescientist703** [comment] 2021-05-25 17:54
It looks like github API has a upper limit of 30 items only. For further items, one need to add page=x parameter to the API request. Thanks for pointing it out I will fix this issue by adding a 'load more' button which when clicked will display all the subsequent issues and pull requests.

**Comment by codescientist703** [comment] 2021-05-28 16:10
Hey, @wopian , The issue is now fixed. I have added the load more button and all your pull requests and issue will be listed. Unfortunately, I have to remove autosuggest functionality because GitHub API does not list the parent of the forked repository. It is only there in GraphQL.

The website link is also changed - you can access your own chart here - 

[https://codescientist703.github.io/kanban-chart/?user=wopian](https://codescientist703.github.io/kanban-chart/?user=wopian.)

**Comment by codescientist703** [comment] 2021-05-28 16:15
To search for pull requests and issues for a particular repository you can type 'chrislgarry/Apollo-11' in the search box and click on submit button.

**Comment by wopian** [comment] 2021-05-28 16:43
This change works perfectly 👍

**Closed as completed** 2021-05-29 08:28 UTC
